### ISSUE TITLE
Lack of crops in dataset

### ISSUE THREAD

**Issue by sitanshu05** [sitanshu05/Effect-of-cimate-change-on-Agriculture#13]
There are only 22 crops in the cropRecommendation Dataset we need to add more crops the dataset also lacks staple crops such as wheat,millets hence they should be added

**Comment by tanvibhujannavar** [comment]
I have added all necessary crops into the CSV file and their requirements.
[cropRecommendationfinaledited.csv](https://github.com/sitanshu05/Effect-of-cimate-change-on-Agriculture/files/8590287/cropRecommendationfinaledited.csv)

**Comment by sitanshu05** [comment]
Add the soil requirements @tanvibhujannavar
