### ISSUE TITLE
data cleaning of cropsOfCountries dataset

### ISSUE THREAD

**Issue by sitanshu05** [sitanshu05/Effect-of-cimate-change-on-Agriculture#14]
Reduce the dataset to the selected countries and drop unnecessary columns
-> Reduce countries
->Crops

**Comment by sitanshu05** [comment]
solved

**Comment by tanvibhujannavar** [comment]
the dataset does not contain these crops or named differently:

label
apple
banana
blackgram
chickpea
coconut
coffee
cotton
lentil
kidneybean
mango
mothbeans
mungbean
muskmelon
orange
papaya
pigeonpeas
pomegranate
rice
watermelon
wheat
sugarcane
oilseeds
millets
apricots
opium
