### ISSUE TITLE
Temperature Dataset

### ISSUE THREAD

**Issue by sitanshu05** [sitanshu05/Effect-of-cimate-change-on-Agriculture#4]
Should we use mean temp or a combination of min and max temperature

I think we can use min max temperature and then see if the required crop temperature is within the range

**Comment by sitanshu05** [comment]
another possible solution:
We can use mean temp and define a +|- x, so that if the temperature is within that range we can say that it is favorable for the crop

**Comment by Abhishek-masur** [comment]
In my point of view it's better to use mean temperature if it's not available we can calculate with help of Max and min
